language: node_js
node_js:
- node
deploy:
  api_key:
    secure: LDa0aGCacfGBTnUIJJ11TB/nZNQgX2ggw9YGI6GK7aYy8yjEIfVBy7xJEnnMcbwmVCWbwut1oMk5rtz19SG+tguDb8CTNHvP4wD3qIDpej8BDAqAzqTqoq7QY2ntqv7Gh71r8hJriujVP85kflgIWcQxQQvPZkyJOcObDNYPnJA9isN4Wz+flBD9pu3eSg7qxjLBAPOjca1aW95eXQirwmrB/2MroGanQU4iLgETfhXun0Bh58ihPg0W8mc3sxqvOYhMNzDR5/WjUv9rWeg3ag4cAiPciL3nKz2MvGLuj20b0eCX8EUh/AlOyP/Ij5YTGaHMoSA6voQvgEK+yFAdkJFVlKzGmAhgYwPe5BKTHMQgjc7N0lDkBg4hHy3x2Q0AAuCOyuYdZtMqYajwdRB34nyStUGmhM/EZAUEmrIL10vLpljUxCy6rV3hHGjXmoyVx7NFsAL9fLmdGwisZmloKjH8OeCiIxCR4zKGlO0rpPCcJkO08KM39yjFS7t/bZDv5/4l3+7BFuKwkpZXXiBMkp6LJqNOtG0tCWZNAuwpryHdb07E566zlZpD5oBnoykyQTbQzXG4seOJbrrwMmPJW4/uuHZHvUi13L7tnaPs9FwQVKLLYXyXEFvPhywA7zfKry7hqCg+bpk1130CX+I7O2C+IKEz1jRZAzxA1E7ATvo=
